In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
data = pd.read_html('https://en.wikipedia.org/wiki/Programming_languages_used_in_most_popular_websites')

In [24]:
data

[         Websites Popularity(unique visitors per month)[1]  \
 0       Google[2]                               1600000000
 1        Facebook                               1120000000
 2         YouTube                               1100000000
 3           Yahoo                                750000000
 4            Etsy                          516,000,000[15]
 5          Amazon                                500000000
 6       Wikipedia                                475000000
 7          Fandom                          315,000,000[22]
 8         Twitter                                290000000
 9            Bing                                285000000
 10           eBay                                285000000
 11            MSN                                280000000
 12       LinkedIn                                260000000
 13      Pinterest                                250000000
 14  WordPress.com                                240000000

     Front-end(Client-side)                              Back-end(Server-side)  \
 0   JavaScript, TypeScript                  C, C++, Go,[3] Java, Python, Node
 1               JavaScript  Hack, PHP (HHVM), Python, C++, Java, Erlang, D...
 2   JavaScript, TypeScript                  C, C++, Python, Java, [11] Go[12]
 3               JavaScript                                                PHP
 4               JavaScript                                        PHP[16][17]
 5               JavaScript                                Java, C++, Perl[19]
 6               JavaScript                                                PHP
 7               JavaScript                                                PHP
 8               JavaScript                     C++, Java,[23] Scala,[24] Ruby
 9               JavaScript                                            C++, C#
 10              JavaScript                Java,[26] JavaScript,[27] Scala[28]
 11              JavaScript                                                 C#
 12              JavaScript                        Java, JavaScript,[29] Scala
 13              JavaScript                        Python (Django),[32] Erlang
 14              JavaScript                                            PHP[34]

                                       Database  \
 0                      Bigtable,[4] MariaDB[5]
 1      MariaDB, MySQL,[9] HBase, Cassandra[10]
 2             Vitess, BigTable, MariaDB[5][13]
 3   PostgreSQL, HBase, Cassandra, MongoDB,[14]
 4                             MySQL, Redis[18]
 5           DynamoDB, RDS/Aurora, Redshift[20]
 6                                  MariaDB[21]
 7                                        MySQL
 8                                    MySQL[25]
 9              Microsoft SQL Server, Cosmos DB
 10                             Oracle Database
 11                        Microsoft SQL Server
 12                              Venice[30][31]
 13                            MySQL, Redis[33]
 14                                 MariaDB[35]

                                                 Notes
 0            The most used search engine in the world
 1             The most visited social networking site
 2   The most popular video sharing site [YouTube i...
 3                                                 NaN
 4                                 E-commerce website.
 5          The most used e-commerce site in the world
 6   A free online encyclopedia based on MediaWiki,...
 7                               Wiki hosting service.
 8                              Popular social network
 9                       Search engine from Microsoft.
 10                              Online auction house.
 11  An email client, for simple use. Previously kn...
 12              World's largest professional network.
 13                           Search engine for ideas.
 14                          Website manager software.  ,
          Websites   C#    C  C++    D Erlang   Go Hack Haskell Java  \
 0          Google   No  Yes  Yes   No     No  Yes   No      No  Yes
 1         YouTube   No  Yes  Yes   No     No  Yes   No      No  Yes
 2        Facebook   No   No  Yes  Yes    Yes  Yes  Yes     Yes  Yes
 3           Yahoo   No  Yes  Yes   No     No  Yes   No      No  Yes
 4          Amazon   No   No  Yes   No     No   No   No      No  Yes
 5       Wikipedia   No   No   No   No     No   No   No      No   No
 6         Twitter   No   No  Yes   No     No   No   No      No  Yes
 7            Bing  Yes   No  Yes   No     No   No   No      No   No
 8            eBay   No   No   No   No     No   No   No      No  Yes
 9             MSN  Yes   No   No   No     No   No   No      No   No
 10       LinkedIn   No   No   No   No     No   No   No      No  Yes
 11      Pinterest   No   No   No   No    Yes   No   No      No   No
 12  WordPress.com   No   No   No   No     No   No   No      No   No

    JavaScript Perl  PHP Python Ruby Scala  XHP
 0         Yes   No   No    Yes   No    No   No
 1          No   No   No    Yes   No    No   No
 2          No   No  Yes    Yes   No    No  Yes
 3         Yes  Yes  Yes    Yes  Yes   Yes   No
 4          No  Yes   No     No   No    No   No
 5          No   No  Yes     No   No    No   No
 6          No   No   No     No  Yes   Yes   No
 7          No   No   No     No   No    No   No
 8         Yes   No   No     No   No   Yes   No
 9          No   No   No     No   No    No   No
 10        Yes   No   No     No   No   Yes   No
 11         No   No   No    Yes   No    No   No
 12         No   No  Yes     No   No    No   No  ]

In [25]:
df= data[0]

In [26]:
df

,Websites,Popularity(unique visitors per month)[1],Front-end(Client-side),Back-end(Server-side),Database,Notes
0,Google[2],1600000000,"JavaScript, TypeScript","C, C++, Go,[3] Java, Python, Node","Bigtable,[4] MariaDB[5]",The most used search engine in the world
1,Facebook,1120000000,JavaScript,"Hack, PHP (HHVM), Python, C++, Java, Erlang, D...","MariaDB, MySQL,[9] HBase, Cassandra[10]",The most visited social networking site
2,YouTube,1100000000,"JavaScript, TypeScript","C, C++, Python, Java, [11] Go[12]","Vitess, BigTable, MariaDB[5][13]",The most popular video sharing site [YouTube i...
3,Yahoo,750000000,JavaScript,PHP,"PostgreSQL, HBase, Cassandra, MongoDB,[14]",NaN
4,Etsy,"516,000,000[15]",JavaScript,PHP[16][17],"MySQL, Redis[18]",E-commerce website.
5,Amazon,500000000,JavaScript,"Java, C++, Perl[19]","DynamoDB, RDS/Aurora, Redshift[20]",The most used e-commerce site in the world
6,Wikipedia,475000000,JavaScript,PHP,MariaDB[21],"A free online encyclopedia based on MediaWiki,..."
7,Fandom,"315,000,000[22]",JavaScript,PHP,MySQL,Wiki hosting service.
8,Twitter,290000000,JavaScript,"C++, Java,[23] Scala,[24] Ruby",MySQL[25],Popular social network
9,Bing,285000000,JavaScript,"C++, C#","Microsoft SQL Server, Cosmos DB",Search engine from Microsoft.
10,eBay,285000000,JavaScript,"Java,[26] JavaScript,[27] Scala[28]",Oracle Database,Online auction house.
11,MSN,280000000,JavaScript,C#,Microsoft SQL Server,"An email client, for simple use. Previously kn..."
12,LinkedIn,260000000,JavaScript,"Java, JavaScript,[29] Scala",Venice[30][31],World's largest professional network.
13,Pinterest,250000000,JavaScript,"Python (Django),[32] Erlang","MySQL, Redis[33]",Search engine for ideas.
14,WordPress.com,240000000,JavaScript,PHP[34],MariaDB[35],Website manager software.

In [27]:
websites = df['Websites']
unique_visitor_per_month = df['Popularity(unique visitors per month)[1]']
exp=[0.25,0.25,0.25,0,0,0,0,0,0,0,0,0,0,]
plt.pie(unique_visitor_per_month, labels = websites, shadow= True, radius= 2, autopct='%2.1f%%',explode=exp)
plt.show()

TypeError: 'type' object is not iterable